volumes:
  tg_data:
  openvpn_data:

networks:
  tg_net:

services:
  database:
    image: postgres:17-alpine
    container_name: tgdb_container
    env_file: .env
    volumes:
      - tg_data:/var/lib/postgresql/tgdata
    ports:
      - "${DB_PORT}:5432"
    networks:
      - tg_net
    restart: unless-stopped

  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn_container
    cap_add:
      - NET_ADMIN
    volumes:
      - openvpn_data:/etc/openvpn
    ports:
      - "1194:1194/udp"
    networks:
      - tg_net
    restart: unless-stopped