volumes:
  livpnet_data:

services:
  database:
    image: postgres:17-alpine
    container_name: db_livpnet
    env_file: .env
    volumes:
      - livpnet_data:/var/lib/postgresql/vpn_data
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

  # backend:
  #   build: ./backend
  #   container_name: backend_livpnet
  #   volumes:
  #     - ./logs:/app/logs
  #     - uploads_attaches:/app/uploads_attaches
  #   env_file: .env
  #   restart: unless-stopped
  #   depends_on:
  #     - database
  #   ports:
  #     - "${APP_PORT}:${APP_PORT}"

  # tgbot:
  #   build: ./tgbot
  #   container_name: tgbot_livpnet
  #   env_file: .env
  #   ports:
  #     - 9184:9184
  #   restart: unless-stopped