volumes:
  tg_data:

services:
  database:
    image: postgres:17-alpine
    container_name: tgdb_container
    env_file: .env
    volumes:
      - tg_data:/var/lib/postgresql/tgdata
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped