servers = [
    {'ip_add': '0.0.0.0',
     'protocol': 'OpenVPN',
     'is_active': 'True',
     'max_cert': 10,
     'count_cert': 2,
     'region': {'id': 0,
                'code': 'RU',
                'name': 'Russia'}},
    {'ip_add': '1.1.1.1',
     'protocol': 'Vless',
     'is_active': 'True',
     'max_cert': 10,
     'count_cert': 4,
     'region': {'id': 1,
                'code': 'PL',
                'name': 'Poland'}},
    {'ip_add': '2.2.2.2',
     'protocol': 'Vless',
     'is_active': 'True',
     'max_cert': 10,
     'count_cert': 7,
     'region': {'id': 1,
                'code': 'PL',
                'name': 'Poland'}},
    {'ip_add': '3.3.3.3',
     'protocol': 'OpenVPN',
     'is_active': 'True',
     'max_cert': 10,
     'count_cert': 7,
     'region': {'id': 1,
                'code': 'NL',
                'name': 'Netherland'}}
]

subscription_1 = {'user_id': 1,
                  'type': 'trial',
                  'region': {'id': 1,
                             'code': 'NL',
                             'name': 'Netherland'},
                  'start_date': '13.05.2025',
                  'end_date': '18.05.2025',
                  'is_active': 'True',
                  'updated_at': '17.05.2025',
                  'file': 'url://for-connect/to-vpn'}

subscription_2 = {'user_id': 2,
                  'type': '2_device',
                  'region': {'id': 2,
                             'code': 'PL',
                             'name': 'Poland'},
                  'start_date': '14.05.2025',
                  'end_date': '24.06.2025',
                  'is_active': 'True',
                  'updated_at': '16.05.2025',
                  'file': 'url://for-connect/to-vpn'}

user_1 = {'id': 1,
          'username': 'Daniil',
          'refer_from': None,
          'reg_data': '13.05.2025',
          'ref_count': 1,
          'subscription': {'user_id': 1,
                           'type': 'trial',
                           'region': {'id': 1,
                                      'code': 'NL',
                                      'name': 'Netherland'},
                           'start_date': '13.05.2025',
                           'end_date': '18.05.2025',
                           'is_active': 'True',
                           'updated_at': '17.05.2025',
                           'file': 'url://for-connect/to-vpn'}}

user_2 = {'id': 2,
          'username': 'Jenya',
          'refer_from': 1,
          'reg_data': '14.05.2025',
          'ref_count': 0,
          'subscription': None}
