"""Add field in server

Revision ID: c366ee1e71c9
Revises: 3c9e02eca479
Create Date: 2025-06-13 18:24:37.877699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c366ee1e71c9'
down_revision: Union[str, None] = '3c9e02eca479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('domain_name', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'server', ['domain_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'server', type_='unique')
    op.drop_column('server', 'domain_name')
    # ### end Alembic commands ###
