"""new field for payment

Revision ID: 6a46e5f37f08
Revises: 8adde31b0f9a
Create Date: 2025-06-23 23:07:46.772154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a46e5f37f08'
down_revision: Union[str, None] = '8adde31b0f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate', 'filename',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.add_column('payment', sa.Column('intent_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'intent_data')
    op.alter_column('certificate', 'filename',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
