class SettingFieldDB:
    DEFAULT_FOR_COUNT = 0
    DEFAULT_MAX_CERT = 10
    DEFAULT_ACTIVE_SRV = False
    DEFAULT_ACTIVE_SUB = False
    MAX_LENGTH_CODE_REGION = 2
    MAX_LENGTH_NAME = 64
    MAX_LENGTH_IP = 16
    MAX_LENGTH_PROTOCOL = 16
    MAX_LENGTH_FILENAME = 64
    MAX_LENGTH_TYPE_SUB = 64
